[build]
  functions = "netlify/functions"

[functions]
  python_version = "3.8"

[[redirects]]
  from = "/api/upload"
  to = "/.netlify/functions/upload"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
